name: Building Wasm binary using Cargo

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  # Target triple
  TARGET: wasm32-unknown-unknown
  # Either debug or release
  OPTIMISATION: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          rustup target add wasm32-unknown-unknown 
          cargo build --target ${TARGET} --${OPTIMISATION}
          tree -L 3 target
      - name: move assets to published artifact
        run: |
          mv target/${TARGET}/${OPTIMISATION}/womans-day-mini-game.wasm public/wasm.wasm
          mv assets public/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4