name: Nix + Wasm example project

on:
  pull_request:
  push:
    branches:
      - main

env:
  REPO: ${{ github.event.repository.name }}

jobs:
  ci:
    runs-on: nixos/nix
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: nix flake check
        run: |
          nix flake check --all-systems

      - name: Display package contents
        run: |
          nix build
          nix develop --command tree ./result
      - uses: actions/upload-artifact@v4
        with:
          name: mini-game.wasm
          path: result/bin/womans-day-mini-game.wasm
